# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class MeshServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunFunc = channel.unary_unary(
                '/example.MeshService/RunFunc',
                request_serializer=service__pb2.RunFuncRequest.SerializeToString,
                response_deserializer=service__pb2.RunFuncResponse.FromString,
                )
        self.QueryRunState = channel.unary_unary(
                '/example.MeshService/QueryRunState',
                request_serializer=service__pb2.QueryRunStateRequest.SerializeToString,
                response_deserializer=service__pb2.QueryRunStateResponse.FromString,
                )
        self.CancelJob = channel.unary_unary(
                '/example.MeshService/CancelJob',
                request_serializer=service__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=service__pb2.CancelJobResponse.FromString,
                )


class MeshServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunFunc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryRunState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeshServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunFunc': grpc.unary_unary_rpc_method_handler(
                    servicer.RunFunc,
                    request_deserializer=service__pb2.RunFuncRequest.FromString,
                    response_serializer=service__pb2.RunFuncResponse.SerializeToString,
            ),
            'QueryRunState': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryRunState,
                    request_deserializer=service__pb2.QueryRunStateRequest.FromString,
                    response_serializer=service__pb2.QueryRunStateResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=service__pb2.CancelJobRequest.FromString,
                    response_serializer=service__pb2.CancelJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.MeshService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MeshService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunFunc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.MeshService/RunFunc',
            service__pb2.RunFuncRequest.SerializeToString,
            service__pb2.RunFuncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryRunState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.MeshService/QueryRunState',
            service__pb2.QueryRunStateRequest.SerializeToString,
            service__pb2.QueryRunStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.MeshService/CancelJob',
            service__pb2.CancelJobRequest.SerializeToString,
            service__pb2.CancelJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
