# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blendercvt.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62lendercvt.proto\"A\n\x16\x43onvertObjToGlbRequest\x12\x12\n\ninput_file\x18\x01 \x01(\t\x12\x13\n\x0boutput_file\x18\x02 \x01(\t\"A\n\x16\x43onvertGlbToObjRequest\x12\x12\n\ninput_file\x18\x01 \x01(\t\x12\x13\n\x0boutput_file\x18\x02 \x01(\t\"\x1f\n\x0c\x43onvertReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xab\x01\n\nBlendercvt\x12;\n\x0f\x43onvertObjToGlb\x12\x17.ConvertObjToGlbRequest\x1a\r.ConvertReply\"\x00\x12;\n\x0f\x43onvertGlbToObj\x12\x17.ConvertGlbToObjRequest\x1a\r.ConvertReply\"\x00\x12#\n\x08Shutdown\x12\x06.Empty\x1a\r.ConvertReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blendercvt_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONVERTOBJTOGLBREQUEST']._serialized_start=20
  _globals['_CONVERTOBJTOGLBREQUEST']._serialized_end=85
  _globals['_CONVERTGLBTOOBJREQUEST']._serialized_start=87
  _globals['_CONVERTGLBTOOBJREQUEST']._serialized_end=152
  _globals['_CONVERTREPLY']._serialized_start=154
  _globals['_CONVERTREPLY']._serialized_end=185
  _globals['_EMPTY']._serialized_start=187
  _globals['_EMPTY']._serialized_end=194
  _globals['_BLENDERCVT']._serialized_start=197
  _globals['_BLENDERCVT']._serialized_end=368
# @@protoc_insertion_point(module_scope)
