# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: srgen.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsrgen.proto\x12\x05srgen\"k\n\nJobRequest\x12\"\n\ttask_type\x18\x01 \x01(\x0e\x32\x0f.srgen.TaskEnum\x12\x12\n\ninput_path\x18\x02 \x01(\t\x12\x13\n\x0bout_img_dir\x18\x03 \x01(\t\x12\x10\n\x08up_scale\x18\x04 \x01(\x05\"x\n\x08JobReply\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\x12$\n\x06status\x18\x02 \x01(\x0e\x32\x14.srgen.JobStatusEnum\x12\x16\n\x0e\x65stimated_time\x18\x03 \x01(\x05\x12\x0f\n\x07results\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"#\n\x10JobStatusRequest\x12\x0f\n\x07job_ids\x18\x01 \x03(\x05\"5\n\x0eJobStatusReply\x12#\n\njob_status\x18\x01 \x03(\x0b\x32\x0f.srgen.JobReply\"\'\n\x0f\x41\x64\x64itionRequest\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\"\n\x10\x41\x64\x64itionResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05*\x1e\n\nStatusEnum\x12\x06\n\x02OK\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01*\x16\n\x08TaskEnum\x12\n\n\x06IMG_SR\x10\x00*:\n\rJobStatusEnum\x12\x0c\n\x08\x46INISHED\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\x0f\n\x0bIN_PROGRESS\x10\x02\x32\xae\x01\n\x05Srgen\x12.\n\x06NewJob\x12\x11.srgen.JobRequest\x1a\x0f.srgen.JobReply\"\x00\x12=\n\tQueryJobs\x12\x17.srgen.JobStatusRequest\x1a\x15.srgen.JobStatusReply\"\x00\x12\x36\n\x03\x41\x64\x64\x12\x16.srgen.AdditionRequest\x1a\x17.srgen.AdditionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'srgen_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUSENUM']._serialized_start=422
  _globals['_STATUSENUM']._serialized_end=452
  _globals['_TASKENUM']._serialized_start=454
  _globals['_TASKENUM']._serialized_end=476
  _globals['_JOBSTATUSENUM']._serialized_start=478
  _globals['_JOBSTATUSENUM']._serialized_end=536
  _globals['_JOBREQUEST']._serialized_start=22
  _globals['_JOBREQUEST']._serialized_end=129
  _globals['_JOBREPLY']._serialized_start=131
  _globals['_JOBREPLY']._serialized_end=251
  _globals['_JOBSTATUSREQUEST']._serialized_start=253
  _globals['_JOBSTATUSREQUEST']._serialized_end=288
  _globals['_JOBSTATUSREPLY']._serialized_start=290
  _globals['_JOBSTATUSREPLY']._serialized_end=343
  _globals['_ADDITIONREQUEST']._serialized_start=345
  _globals['_ADDITIONREQUEST']._serialized_end=384
  _globals['_ADDITIONRESPONSE']._serialized_start=386
  _globals['_ADDITIONRESPONSE']._serialized_end=420
  _globals['_SRGEN']._serialized_start=539
  _globals['_SRGEN']._serialized_end=713
# @@protoc_insertion_point(module_scope)
