# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: texcreator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10texcreator.proto\x12\ntexcreator\"\x9a\x01\n\nJobRequest\x12\'\n\ttask_type\x18\x01 \x01(\x0e\x32\x14.texcreator.TaskEnum\x12\x0e\n\x06in_obj\x18\x02 \x01(\t\x12\x10\n\x08in_condi\x18\x03 \x01(\t\x12\x0f\n\x07out_obj\x18\x04 \x01(\t\x12\x15\n\rout_debug_dir\x18\x05 \x01(\t\x12\x19\n\x11\x64\x65\x62ug_paste_condi\x18\x06 \x01(\t\"}\n\x08JobReply\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\x12)\n\x06status\x18\x02 \x01(\x0e\x32\x19.texcreator.JobStatusEnum\x12\x16\n\x0e\x65stimated_time\x18\x03 \x01(\x05\x12\x0f\n\x07results\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"#\n\x10JobStatusRequest\x12\x0f\n\x07job_ids\x18\x01 \x03(\x05\":\n\x0eJobStatusReply\x12(\n\njob_status\x18\x01 \x03(\x0b\x32\x14.texcreator.JobReply\"\'\n\x0f\x41\x64\x64itionRequest\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\"\n\x10\x41\x64\x64itionResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05*\x1e\n\nStatusEnum\x12\x06\n\x02OK\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01*+\n\x08TaskEnum\x12\x0f\n\x0bTEX_CREATOR\x10\x00\x12\x0e\n\nTEX_REFINE\x10\x01*:\n\rJobStatusEnum\x12\x0c\n\x08\x46INISHED\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\x0f\n\x0bIN_PROGRESS\x10\x02\x32\xd1\x01\n\nTexcreator\x12\x38\n\x06NewJob\x12\x16.texcreator.JobRequest\x1a\x14.texcreator.JobReply\"\x00\x12G\n\tQueryJobs\x12\x1c.texcreator.JobStatusRequest\x1a\x1a.texcreator.JobStatusReply\"\x00\x12@\n\x03\x41\x64\x64\x12\x1b.texcreator.AdditionRequest\x1a\x1c.texcreator.AdditionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'texcreator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUSENUM']._serialized_start=490
  _globals['_STATUSENUM']._serialized_end=520
  _globals['_TASKENUM']._serialized_start=522
  _globals['_TASKENUM']._serialized_end=565
  _globals['_JOBSTATUSENUM']._serialized_start=567
  _globals['_JOBSTATUSENUM']._serialized_end=625
  _globals['_JOBREQUEST']._serialized_start=33
  _globals['_JOBREQUEST']._serialized_end=187
  _globals['_JOBREPLY']._serialized_start=189
  _globals['_JOBREPLY']._serialized_end=314
  _globals['_JOBSTATUSREQUEST']._serialized_start=316
  _globals['_JOBSTATUSREQUEST']._serialized_end=351
  _globals['_JOBSTATUSREPLY']._serialized_start=353
  _globals['_JOBSTATUSREPLY']._serialized_end=411
  _globals['_ADDITIONREQUEST']._serialized_start=413
  _globals['_ADDITIONREQUEST']._serialized_end=452
  _globals['_ADDITIONRESPONSE']._serialized_start=454
  _globals['_ADDITIONRESPONSE']._serialized_end=488
  _globals['_TEXCREATOR']._serialized_start=628
  _globals['_TEXCREATOR']._serialized_end=837
# @@protoc_insertion_point(module_scope)
