# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teximguv.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eteximguv.proto\x12\x08teximguv\"\xdc\x01\n\nJobRequest\x12%\n\ttask_type\x18\x01 \x01(\x0e\x32\x12.teximguv.TaskEnum\x12\x0e\n\x06in_obj\x18\x02 \x01(\t\x12\x14\n\x0cout_objs_dir\x18\x03 \x01(\t\x12\x12\n\nin_prompts\x18\x04 \x01(\t\x12\x14\n\x0cin_condi_img\x18\x05 \x01(\t\x12\x0e\n\x06uv_res\x18\x06 \x01(\x05\x12\x1b\n\x13num_inference_steps\x18\x07 \x01(\x05\x12\x16\n\x0eguidance_scale\x18\x08 \x01(\x02\x12\x12\n\ndebug_save\x18\t \x01(\x08\"{\n\x08JobReply\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\x12\'\n\x06status\x18\x02 \x01(\x0e\x32\x17.teximguv.JobStatusEnum\x12\x16\n\x0e\x65stimated_time\x18\x03 \x01(\x05\x12\x0f\n\x07results\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"#\n\x10JobStatusRequest\x12\x0f\n\x07job_ids\x18\x01 \x03(\x05\"8\n\x0eJobStatusReply\x12&\n\njob_status\x18\x01 \x03(\x0b\x32\x12.teximguv.JobReply\"\'\n\x0f\x41\x64\x64itionRequest\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\"\n\x10\x41\x64\x64itionResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05*\x1e\n\nStatusEnum\x12\x06\n\x02OK\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01**\n\x08TaskEnum\x12\r\n\tTEX_IMGUV\x10\x00\x12\x0f\n\x0bTEX_CONTROL\x10\x01*:\n\rJobStatusEnum\x12\x0c\n\x08\x46INISHED\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\x0f\n\x0bIN_PROGRESS\x10\x02\x32\xc3\x01\n\x08Teximguv\x12\x34\n\x06NewJob\x12\x14.teximguv.JobRequest\x1a\x12.teximguv.JobReply\"\x00\x12\x43\n\tQueryJobs\x12\x1a.teximguv.JobStatusRequest\x1a\x18.teximguv.JobStatusReply\"\x00\x12<\n\x03\x41\x64\x64\x12\x19.teximguv.AdditionRequest\x1a\x1a.teximguv.AdditionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'teximguv_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUSENUM']._serialized_start=548
  _globals['_STATUSENUM']._serialized_end=578
  _globals['_TASKENUM']._serialized_start=580
  _globals['_TASKENUM']._serialized_end=622
  _globals['_JOBSTATUSENUM']._serialized_start=624
  _globals['_JOBSTATUSENUM']._serialized_end=682
  _globals['_JOBREQUEST']._serialized_start=29
  _globals['_JOBREQUEST']._serialized_end=249
  _globals['_JOBREPLY']._serialized_start=251
  _globals['_JOBREPLY']._serialized_end=374
  _globals['_JOBSTATUSREQUEST']._serialized_start=376
  _globals['_JOBSTATUSREQUEST']._serialized_end=411
  _globals['_JOBSTATUSREPLY']._serialized_start=413
  _globals['_JOBSTATUSREPLY']._serialized_end=469
  _globals['_ADDITIONREQUEST']._serialized_start=471
  _globals['_ADDITIONREQUEST']._serialized_end=510
  _globals['_ADDITIONRESPONSE']._serialized_start=512
  _globals['_ADDITIONRESPONSE']._serialized_end=546
  _globals['_TEXIMGUV']._serialized_start=685
  _globals['_TEXIMGUV']._serialized_end=880
# @@protoc_insertion_point(module_scope)
